var s = "Anderson \"Spider\" Silva Minotauro \\Nogueira".toLowerCase();
console.log(s + '\n')
console.log(s.charAt(0))
console.log(s.charAt(s.length-1))
console.log(s.substring(2,8))
console.log(s.slice(8,22))
console.log(s.slice(-6))
console.log(s.indexOf("a"))
console.log(s.lastIndexOf("a"))
console.log(s.split(", "))
console.log(s.replace("a","A"))
console.log(s[5])
console.log(s.substring(s.indexOf(" ")+1, s.length))